package zheng.python.scilearn;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Tue Dec 11 15:42:50 EST 2012
 */

public interface Predictor {

    public Double predict(String inst_str) throws com.bitmechanic.barrister.RpcException;

}

